In [1]:
import math
r = math.sin(math.pi/3)
print(f"sin(pi/3) = {round(r,2)}")

sin(pi/3) = 0.87


In [2]:
!pip install numpy

In [3]:
import numpy as np
np.__version__

'1.19.4'

In [4]:
import numpy as np
I_m = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I_m

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
np.mat("1 2 3; 4 5 6")

matrix([[1, 2, 3],
        [4, 5, 6]])

In [15]:
a = np.array([[1, 4], [8, 9]])
b = np.array([[2, 3], [7, 11]])
a + b

array([[ 3,  7],
       [15, 20]])

In [17]:
ma = np.mat("1 4; 8 9")
mb = np.mat("2 3; 7 11")
ma + mb

matrix([[ 3,  7],
        [15, 20]])

In [18]:
print(f'array: ', 7 * a)
print("")
print('mat: ', 7 * ma)

array:  [[ 7 28]
 [56 63]]

mat:  [[ 7 28]
 [56 63]]


In [19]:
a * b

array([[ 2, 12],
       [56, 99]])

In [20]:
ma * mb

matrix([[ 30,  47],
        [ 79, 123]])

In [21]:
np.dot(a, b)

array([[ 30,  47],
       [ 79, 123]])

In [23]:
sm = np.array([[1, 0, 2, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 3, 0, 0, 0, 0, 0]])
sm

array([[1, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0]])

In [24]:
from scipy.sparse import csr_matrix
row = np.array([0, 0, 2])
col = np.array([0, 2, 2])
data = np.array([1, 2, 3])
csrm = csr_matrix((data, (row, col)), shape=(3, 8))
csrm

<3x8 sparse matrix of type '<class 'numpy.longlong'>'
	with 3 stored elements in Compressed Sparse Row format>

In [25]:
csrm.toarray()

array([[1, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0]], dtype=int64)

In [26]:
A = np.mat("-1 3 -5; 2 -2 4; 1 3 0")
b = np.mat('-3 8 6').T
r = np.linalg.solve(A, b)
print(r)

[[ 4.5]
 [ 0.5]
 [-0. ]]


In [27]:
A = np.mat("1 3 -4 2;3 -1 2 -1;-2 4 -1 3;3 0 -7 6")
b = np.mat("0 0 0 0").T
r = np.linalg.solve(A, b)
print(r)

[[ 0.]
 [ 0.]
 [-0.]
 [ 0.]]


In [29]:
from sympy import *
from sympy.solvers.solveset import linsolve
x1, x2, x3, x4 = symbols("x1 x2 x3 x4")
linsolve([x1 + 3*x2 - 4*x3 + 2*x4, 
          3*x1 - x2 + 2*x3 - x4, 
          -2*x1 + 4*x2 - x3 + 3*x4, 
          3*x1 +9*x2 - 7*x3 + 6*x4], 
         (x1, x2, x3, x4))

FiniteSet((x4/10, -7*x4/10, 0, x4))

In [30]:
from scipy.stats import chisquare
chisquare([1e10-1e6, 1e10+1.5e6, 
           1e10-2e6, 1e10+4e6, 1e10-3e6, 1e10+0.5e6])

Power_divergenceResult(statistic=3250.0, pvalue=0.0)

In [31]:
from scipy.stats import chi2 
chi2.isf(0.05, (6-1))

11.070497693516355

In [32]:
p_value = 1 - chi2.cdf(3250.0, (6-1)) 
print(p_value)

0.0
